version: "3"
services:
  free-radius:
    build: 
      context: freeradius-dockerfile
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    networks:
      - webnet
    environment:
      - "TZ=Europe/Amsterdam"
networks:
  webnet:
