version: "3"
services:
  free-radius:
    image: freeradius/freeradius-server:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "1812:1812"
      - "1813:1813"
      - "22:8822"
    user: "0"
    networks:
      - webnet
    environment:
      - "TZ=Europe/Amsterdam"
    volumes:
      - "./raddb/clients.conf:/etc/raddb/clients.conf"
      - "./raddb/mods-config/files/authorise:/etc/raddb/mods-config/files/authorise"
networks:
  webnet:
